In [24]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import time

options = webdriver.ChromeOptions()
options.add_argument("--headless")  # Remove this line to see browser window
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

base_url = "https://www.paulaschoice.com/ingredient-dictionary?start=2000&sz=2000"  # Show all ingredients

print("Loading page...")
driver.get(base_url)
time.sleep(5)  # Wait for JS to load; adjust if needed

ingredients = []

rows = driver.find_elements(By.CSS_SELECTOR, ".IngredientList__IngredientRow-sc-12d8srs-5")
print(f"Found {len(rows)} ingredient rows.")

for row in rows:
    try:
        name = row.find_element(By.CSS_SELECTOR, ".IngredientList__Name-sc-12d8srs-10").text.strip()
        description = row.find_element(By.CSS_SELECTOR, ".IngredientList__Description-sc-12d8srs-11").text.strip()
        rating = row.find_element(By.CSS_SELECTOR, ".ColoredIngredientRating__Rating-sc-8nrs1d-0").text.strip()
    except:
        name, description, rating = "", "", ""

    ingredients.append({
        "Name": name,
        "Description": description,
        "Rating": rating
    })

driver.quit()

df = pd.DataFrame(ingredients)
df.to_csv("paulaschoice_us_ingredients.csv", index=False)

print(f"✅ Done! Scraped {len(ingredients)} ingredients.")

Loading page...
Found 2000 ingredient rows.
✅ Done! Scraped 2000 ingredients.

In [25]:
import pandas as pd

# Load the raw scraped data
df = pd.read_csv('paulaschoice_us_ingredients.csv')
df

,Name,Description,Rating
0,Cranberry Seed Extract,Natural ingredient derived from antioxidant/om...,AVERAGE
1,Crataegus Monogyna Extract,"Also known as hawthorn berry, this plant extra...",AVERAGE
2,D&C,"According to the FDA, D&C is an identification...",AVERAGE
3,D&C Colors,General term for a wide group of color additiv...,AVERAGE
4,Daucus Carota,Also known as wild carrot. An antioxidant-rich...,AVERAGE
...,...,...,...
28016,Zostera Marina Extract,Functions: Skin Conditioning. We have not yet ...,NOT RATED
28017,Zygophyllum Qatarense Leaf/Stem Extract,Functions: Antioxidant. We have not yet rated ...,NOT RATED
28018,Zygosaccharomyces Microellipsoides Ferment,Functions: Humectant. We have not yet rated th...,NOT RATED
28019,Zymomonas Ferment Extract,"Functions: Humectant, Skin Conditioning. We ha...",NOT RATED
28020,Zymomonas Ferment Filtrate,"Functions: Humectant, Skin Conditioning. We ha...",NOT RATED

In [26]:
# Cleaning steps
df['Name'] = df['Name'].str.strip()
df['Description'] = df['Description'].str.strip()
df['Rating'] = df['Rating'].str.strip().str.lower()

# Optional: Remove duplicates (if any)
df = df.drop_duplicates(subset='Name')

df

,Name,Description,Rating
0,Cranberry Seed Extract,Natural ingredient derived from antioxidant/om...,average
1,Crataegus Monogyna Extract,"Also known as hawthorn berry, this plant extra...",average
2,D&C,"According to the FDA, D&C is an identification...",average
3,D&C Colors,General term for a wide group of color additiv...,average
4,Daucus Carota,Also known as wild carrot. An antioxidant-rich...,average
...,...,...,...
28016,Zostera Marina Extract,Functions: Skin Conditioning. We have not yet ...,not rated
28017,Zygophyllum Qatarense Leaf/Stem Extract,Functions: Antioxidant. We have not yet rated ...,not rated
28018,Zygosaccharomyces Microellipsoides Ferment,Functions: Humectant. We have not yet rated th...,not rated
28019,Zymomonas Ferment Extract,"Functions: Humectant, Skin Conditioning. We ha...",not rated
28020,Zymomonas Ferment Filtrate,"Functions: Humectant, Skin Conditioning. We ha...",not rated

In [27]:
# Save cleaned file
df.to_csv('paulaschoice_us_ingredients_clean.csv', index=False)

print(f"✅ Done! Cleaned {len(df)} ingredients and saved to 'paulaschoice_us_ingredients_clean.csv'")

✅ Done! Cleaned 26018 ingredients and saved to 'paulaschoice_us_ingredients_clean.csv'